# PlaceholderAPI Support
# ---
# %player% - Get Player Name
# ---

# EXECUTE
# ---
# CMD : 유저 권한으로 명령어가 실행됩니다
# CMDOP : OP 권한으로 명령어가 실행됩니다
# CMDCON : 콘솔 권한으로 명령어 실행됩니다
# OPENMENU : (EX : OPENMENU:helloworld1) 지정된 메뉴를 오픈합니다.
# ---

# 로비 아이템을 접속시 마다 초기화 합니다.
초기화: true

# 스코어 보드 관련

스코어 보드 활성화: true

업데이트 시간(초): 15

# 서버 최적화/설정 관련

엔티티 소환 차단: true
날씨 차단: true
아이템 드랍 비활성화: true
아이템 획득 비활성화: true

플레이어 허기 비활성화: true
플레이어 채력 비활성화: true
플레이어 PVP 비활성화: true
플레이어 무적: true

# 처음 접속했거나 재접속시 발생하는 이벤트

첫 접속:
  채팅:
    - "안녕하세요 %player%님!"
    - "처음 접속하셨습니다!"
  폭죽: true
#  소리:
#  명령어(콘솔):


재접속:
  채팅:
    - "안녕하세요 %player%님!"
    - "다시 접속해주셔서 감사합니다!"
  폭죽: true
#  소리:
#  명령어(콘솔):

# 슬롯별 아이템 설정 (대문자만 가능) Ex [STONE, count:2, name:제목입니다, lore(0):lore 입니다, lore(1):lore2 입니다, ..., EXECUTE:Put Your Executes]

슬롯:
  1번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  2번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  3번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  4번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  5번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  6번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  7번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  8번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work
  9번:
    아이템: 0
    개수: 1
    이름: 공기
    lore(n): lore
    execute: CMD:tell %player% work

# ---------
# TABLIST |
# ---------

tablist:
  황성화: true

  업데이트:
    활성화: true
    시간(초): 30

    header:
      - ""
      - "VeryServer Season 3 (%player%님 환영합니다)"
      - ""
    footer:
      - ""
      - "디스코드 : https://discord.gg/ABCDEF"
      - ""

# ------------
# SCOREBOARD |
# ------------

