name: $pluginName
version: $pluginVersion
main: $pluginMain
api-version: 1.16
depend: [ Verylib, ProtocolLib, PlaceholderAPI ]
authors: [ TeamVery ]
description: 관리의 잡다한 기능을 추가해줍니다.
website: https://github.com/Kill00

commands:
  manage:
    description: 관리 플러그인 설정 관련 명령어
    permission: op

permissions:
  manage.*:
    description: 관리관련 펄미션
    children:
      lobbya.bypass: true
  manage.bypass:
    default: op
    children:
      manage.bypass.blockplace: true
      manage.bypass.blockbreak: true
      manage.bypass.pickupitem: true
      manage.bypass.dropitem: true
      manage.bypass.interact: true
      manage.bypass.chat: true